name: Run tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run tests in Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: pqfe-tests:latest

      - name: Run tests in container
        run: docker run --rm pqfe-tests:latest
