name: Run tests

on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Cache Docker layers
          uses: actions/cache@v3
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-

        - name: Pull Docker image
          run: docker pull ernessola/pqfe:latest

        - name: Run tests in container
          continue-on-error: false
          env:
            NO_CACHE: ${{ github.event.number }}_${{ github.run_id }}_${{ github.run_attempt }}
          run: |
            docker run --rm \
              -v ${{ github.workspace }}:/ws \
              ernessola/pqfe:latest \
              python -m pytest /ws/tests
